/**
 * Zones cliquables du cabinet.
 * Les coordonnées sont en POURCENTAGE de l'image (scene.png : 1772 × 887 px),
 * mesurées automatiquement à partir de Détails.png.
 *
 *  - cx / cy : centre de la zone (en % de la largeur / hauteur de l'image)
 *  - w / h   : largeur / hauteur de la zone (en %)
 *  - image   : le visuel qui s'affiche dans la pop-up
 *  - title   : légende affichée sous l'image (modifiable / supprimable)
 *
 * Pour ajuster une zone : lancez le site avec  ?debug  à la fin de l'URL
 * (ex. http://localhost:5173/?debug). Les zones deviennent visibles et
 * chaque clic sur la scène affiche ses coordonnées en % dans la console.
 * Il suffit ensuite de recopier les valeurs ici.
 */
const hotspots = [
  {
    id: "01",
    cx: 9.93,
    cy: 12.4,
    w: 5.2,
    h: 14.0,
    image: "assets/details/01.png",
    title: "L'Astronome",
  },
  {
    id: "02",
    cx: 17.27,
    cy: 6.99,
    w: 3.0,
    h: 6.0,
    image: "assets/details/02.png",
    title: "L'Ornithologue",
  },
  {
    id: "03",
    cx: 25.17,
    cy: 8.79,
    w: 4.2,
    h: 12.5,
    image: "assets/details/03.png",
    title: "Premier pas",
  },
  {
    id: "04",
    cx: 31.49,
    cy: 9.58,
    w: 5.0,
    h: 9.5,
    image: "assets/details/04.png",
    title: "L'Aéronaute",
  },
  {
    id: "05",
    cx: 27.65,
    cy: 20.29,
    w: 4.4,
    h: 4.0,
    image: "assets/details/05.png",
    title: "Le Marin",
  },
  {
    id: "06",
    cx: 69.53,
    cy: 18.26,
    w: 5.2,
    h: 9.0,
    image: "assets/details/06.png",
    title: "Le Petit Monstre",
  },
  {
    id: "07",
    cx: 73.36,
    cy: 6.99,
    w: 11.0,
    h: 9.5,
    image: "assets/details/07.png",
    title: "Les Visiteurs",
    sound: 'audio/spots/07.mp3'
  },
  {
    id: "08",
    cx: 87.36,
    cy: 16.01,
    w: 2.6,
    h: 7.0,
    image: "assets/details/08.png",
    title: "Le Comédien",
  },
  {
    id: "09",
    cx: 95.49,
    cy: 19.73,
    w: 7.5,
    h: 14.0,
    image: "assets/details/09.png",
    title: "Le Lutin",
  },
  {
    id: "10",
    cx: 11.68,
    cy: 36.6,
    w: 6.0,
    h: 8.0,
    image: "assets/details/10.png",
    title: "Le Patron du PMU",
  },
  {
    id: "11",
    cx: 11.68,
    cy: 44.9,
    w: 6.0,
    h: 8.0,
    image: "assets/details/11.png",
    title: "Le Turfiste",
  },
  {
    id: "12",
    cx: 18.79,
    cy: 37.88,
    w: 3.8,
    h: 8.5,
    image: "assets/details/12.png",
    title: "L'Oiseau en cage",
  },
  {
    id: "13",
    cx: 27.65,
    cy: 43.74,
    w: 6.5,
    h: 13.5,
    image: "assets/details/13.png",
    title: "Jour de marché",
  },
  {
    id: "14",
    cx: 44.81,
    cy: 38.33,
    w: 3.8,
    h: 14.0,
    image: "assets/details/14.png",
    title: "Le Poilu",
  },
  {
    id: "15",
    cx: 52.37,
    cy: 37.21,
    w: 4.2,
    h: 9.0,
    image: "assets/details/15.png",
    title: "Portrait de famille",
  },
  {
    id: "16",
    cx: 51.69,
    cy: 45.32,
    w: 4.2,
    h: 5.5,
    image: "assets/details/16.png",
    title: "Le Trompettiste",
  },
  // ---- Étage du milieu (suite) ----
  {
    id: "17",
    cx: 61.79,
    cy: 44.59,
    w: 5.4,
    h: 21.8,
    image: "assets/details/17.png",
    title: "Le bureau du détective",
  },
  {
    id: "18",
    cx: 70.77,
    cy: 44.98,
    w: 6.4,
    h: 16.2,
    image: "assets/details/18.png",
    title: "La voyante",
  },
  {
    id: "19",
    cx: 81.32,
    cy: 44.19,
    w: 7.0,
    h: 20.1,
    image: "assets/details/19.png",
    title: "Le laboratoire",
    sound: 'audio/spots/19.mp3'
  },
  {
    id: "20",
    cx: 91.76,
    cy: 45.89,
    w: 7.0,
    h: 21.9,
    image: "assets/details/20.png",
    title: "L'infirmerie",
  },

  // ---- Rez-de-chaussée ----
  {
    id: "21",
    cx: 2.17,
    cy: 79.37,
    w: 4.3,
    h: 9.5,
    image: "assets/details/21.png",
    title: "Le perroquet",
  },
  {
    id: "22",
    cx: 4.32,
    cy: 90.64,
    w: 3.9,
    h: 9.0,
    image: "assets/details/22.png",
    title: "Le tonneau",
  },
  {
    id: "23",
    cx: 13.46,
    cy: 87.77,
    w: 10.3,
    h: 11.8,
    image: "assets/details/23.png",
    title: "La grande malle",
  },
  {
    id: "24",
    cx: 23.79,
    cy: 88.05,
    w: 7.6,
    h: 10.4,
    image: "assets/details/24.png",
    title: "Le train",
    sound: 'audio/spots/24.mp3'
  },

  // 25 / 26 / 27 : un seul ovale sur le plan (la salle à manger),
  // découpé ici en trois bandes de haut en bas. À affiner si besoin.
  {
    id: "25",
    cx: 24.97,
    cy: 64.55,
    w: 11.5,
    h: 6.6,
    image: "assets/details/25.png",
    title: "L'horloge",
  },
  {
    id: "26",
    cx: 24.97,
    cy: 71.2,
    w: 11.5,
    h: 6.6,
    image: "assets/details/26.png",
    title: "Le gâteau",
  },
  {
    id: "27",
    cx: 24.97,
    cy: 77.85,
    w: 11.5,
    h: 6.6,
    image: "assets/details/27.png",
    title: "La table dressée",
  },

  {
    id: "28",
    cx: 35.47,
    cy: 67.31,
    w: 3.3,
    h: 12.0,
    image: "assets/details/28.png",
    title: "L'affiche du cirque",
  },
  {
    id: "29",
    cx: 40.77,
    cy: 66.12,
    w: 3.8,
    h: 10.3,
    image: "assets/details/29.png",
    title: "Le projecteur",
  },
  {
    id: "30",
    cx: 39.19,
    cy: 82.07,
    w: 8.7,
    h: 11.1,
    image: "assets/details/30.png",
    title: "La moto",
    sound: 'audio/spots/30.mp3'
  },
  {
    id: "31",
    cx: 45.91,
    cy: 72.27,
    w: 1.6,
    h: 5.2,
    image: "assets/details/31.png",
    title: "Le petit cadre",
  },

  // 32 / 33 / 34 : un seul ovale sur le plan (le village miniature),
  // découpé en trois bandes de haut en bas.
  {
    id: "32",
    cx: 49.8,
    cy: 73.13,
    w: 3.0,
    h: 3.8,
    image: "assets/details/32.png",
    title: "Curiosité 32",
    sound: 'audio/spots/32.mp3'
  },
  {
    id: "33",
    cx: 49.8,
    cy: 76.89,
    w: 3.0,
    h: 3.8,
    image: "assets/details/33.png",
    title: "Curiosité 33",
    sound: 'audio/spots/33.mp3'
  },
  {
    id: "34",
    cx: 49.8,
    cy: 80.65,
    w: 3.0,
    h: 3.8,
    image: "assets/details/34.png",
    title: "Curiosité 34",
    sound: 'audio/spots/34.mp3'
  },

  {
    id: "35",
    cx: 55.98,
    cy: 76.89,
    w: 3.5,
    h: 7.7,
    image: "assets/details/35.png",
    title: "Le casque et le globe",
  },
  {
    id: "37",
    cx: 65.46,
    cy: 74.41,
    w: 3.1,
    h: 8.8,
    image: "assets/details/37.png",
    title: "La statue",
  },
  {
    id: "38",
    cx: 71.11,
    cy: 75.08,
    w: 5.2,
    h: 19.4,
    image: "assets/details/38.png",
    title: "La cellule",
  },
  {
    id: "39",
    cx: 78.13,
    cy: 71.93,
    w: 4.2,
    h: 21.2,
    image: "assets/details/39.png",
    title: "Le réverbère",
    sound: 'audio/spots/39.mp3'
  },
  {
    id: "40",
    cx: 86.79,
    cy: 70.41,
    w: 2.4,
    h: 13.2,
    image: "assets/details/40.png",
    title: "Salle des fêtes",
  },
  {
    id: "41",
    cx: 90.72,
    cy: 71.36,
    w: 3.6,
    h: 19.2,
    image: "assets/details/41.png",
    title: "Club 80",
  },
  {
    id: "42",
    cx: 95.09,
    cy: 90.64,
    w: 8.0,
    h: 16.7,
    image: "assets/details/42.png",
    title: "Le gramophone",
  },

  // ---- Étage du haut (suite) ----
  {
    id: "43",
    cx: 82.82,
    cy: 17.19,
    w: 3.1,
    h: 5.5,
    image: "assets/details/43.png",
    title: "Le chapiteau",
  },
  {
    id: "47",
    cx: 23.56,
    cy: 21.03,
    w: 1.8,
    h: 3.5,
    image: "assets/details/47.png",
    title: "Le fauteuil rouge",
  },
  {
    id: "48",
    cx: 52.85,
    cy: 19.5,
    w: 4.6,
    h: 6.1,
    image: "assets/details/48.png",
    title: "Les marionnettes",
  },
  {
    id: "50",
    cx: 90.1,
    cy: 14.04,
    w: 1.8,
    h: 4.0,
    image: "assets/details/50.png",
    title: "Curiosité 50",
  },

  // ---- Rez-de-chaussée (suite) ----
  // 44 / 36 : un seul ovale large sur le plan, découpé gauche / droite.
  {
    id: "44",
    cx: 50.6,
    cy: 89.85,
    w: 5.0,
    h: 8.1,
    image: "assets/details/44.png",
    title: "Le paquebot",
  },
  {
    id: "36",
    cx: 56.0,
    cy: 89.85,
    w: 5.0,
    h: 8.1,
    image: "assets/details/36.png",
    title: "Curiosité 36",
  },

  {
    id: "45",
    cx: 59.85,
    cy: 80.05,
    w: 2.8,
    h: 4.7,
    image: "assets/details/45.png",
    title: "Curiosité 45",
  },
  {
    id: "46",
    cx: 11.94,
    cy: 69.17,
    w: 5.5,
    h: 13.6,
    image: "assets/details/46.png",
    title: "La Femme des Marais",
  },
  {
    id: "51",
    cx: 74.1,
    cy: 93.46,
    w: 2.3,
    h: 6.1,
    image: "assets/details/51.png",
    title: "Le médaillon",
  },
  {
    id: "52",
    cx: 83.01,
    cy: 86.87,
    w: 4.0,
    h: 10.5,
    image: "assets/details/52.png",
    title: "Le fauteuil",
  },

  // ---- Les polaroïds sur le fil (lettres A à J) ----
  {
    id: "A",
    cx: 44.2,
    cy: 58.4,
    w: 1.6,
    h: 3.6,
    image: "assets/details/A.png",
    title: "Polaroïd A",
  },
  {
    id: "B",
    cx: 45.74,
    cy: 59.41,
    w: 1.6,
    h: 3.6,
    image: "assets/details/B.png",
    title: "Polaroïd B",
  },
  {
    id: "C",
    cx: 47.32,
    cy: 60.48,
    w: 1.6,
    h: 5.5,
    image: "assets/details/C.png",
    title: "Polaroïd C",
  },
  {
    id: "D",
    cx: 48.96,
    cy: 61.61,
    w: 1.6,
    h: 5.5,
    image: "assets/details/D.png",
    title: "Polaroïd D",
  },
  {
    id: "E",
    cx: 50.87,
    cy: 62.74,
    w: 1.6,
    h: 5.5,
    image: "assets/details/E.png",
    title: "Polaroïd E",
  },
  {
    id: "F",
    cx: 52.79,
    cy: 62.18,
    w: 1.6,
    h: 5.5,
    image: "assets/details/F.png",
    title: "Polaroïd F",
  },
  {
    id: "G",
    cx: 55.16,
    cy: 63.92,
    w: 3.1,
    h: 8.1,
    image: "assets/details/G.png",
    title: "Polaroïd G",
  },
  {
    id: "H",
    cx: 57.9,
    cy: 65.78,
    w: 2.1,
    h: 6.7,
    image: "assets/details/H.png",
    title: "Polaroïd H",
  },
  {
    id: "I",
    cx: 60.81,
    cy: 68.09,
    w: 2.4,
    h: 8.3,
    image: "assets/details/I.png",
    title: "Polaroïd I",
  },
  {
    id: "J",
    cx: 64.08,
    cy: 65.16,
    w: 1.6,
    h: 3.6,
    image: "assets/details/J.png",
    title: "Polaroïd J",
  },
];

/** Zone de l'enseigne « NEZ à NEZ » (position exacte mesurée dans la scène). */
export const signZone = { left: 47.57, top: 2.03, width: 17.33, height: 13.53 }

export default hotspots;
